package com.company.carrental.data.pojo;

// default package
// Generated 17 Nov, 2012 7:41:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.sun.org.apache.bcel.internal.generic.DADD;

/**
 * DriverMaster generated by hbm2java
 */
@Entity
@Table(name = "driver_master", catalog = "Car_Rental")
public class DriverMaster implements java.io.Serializable {

    private Integer driverId;
    private String driverFullName;
    private char gender;
    private Date dob;
    private Float totalExperience;
    private String primaryContactNumber;
    private Integer currentAreaId;
    private String licenceNo;
    private String licenceType;
    private Date licenceExpiryDate;
    private Character jobPrefIndividualTemp;
    private Character jobPrefIndividualPerm;
    private Character jobPrefIndividualAdhoc;
    private Character jobPrefCorporateTemp;
    private Character jobPrefCorporatePerm;
    private Character jobPrefCorporateAdhoc;
    private Character carTypeAutomatic;
    private Character carTypeManual;
    private Integer ratingId;
    private String referenceName;
    private String referenceNumber;
    private String eyeSight;
    private String Diabetes;
    private String medicalHistory;
    private String accidentHistory;

    private Set<DriverContact> driverContacts;
    private Set<DriverAddress> driverAddresses;
    private Set<DriverEducation> driverEducations;
    
    public DriverMaster() {
    }
    
    public DriverMaster(Integer driverId) {
        this.driverId = driverId;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "Driver_Id", unique = true, nullable = false)
    public Integer getDriverId() {
        return this.driverId;
    }

    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    @Column(name = "Driver_FullName", nullable = false)
    public String getDriverFullName() {
        return this.driverFullName;
    }

    public void setDriverFullName(String driverFullName) {
        this.driverFullName = driverFullName;
    }

    @Column(name = "Gender", nullable = false, length = 1)
    public char getGender() {
        return this.gender;
    }

    public void setGender(char gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DOB", length = 0)
    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    @Column(name = "Total_Experience", precision = 12, scale = 0)
    public Float getTotalExperience() {
        return this.totalExperience;
    }

    public void setTotalExperience(Float totalExperience) {
        this.totalExperience = totalExperience;
    }

    @Column(name = "Primary_Contact_Number", nullable = false, length = 16777215)
    public String getPrimaryContactNumber() {
        return this.primaryContactNumber;
    }

    public void setPrimaryContactNumber(String primaryContactNumber) {
        this.primaryContactNumber = primaryContactNumber;
    }

    @Column(name = "Current_Area_Id")
    public Integer getCurrentAreaId() {
        return this.currentAreaId;
    }

    public void setCurrentAreaId(Integer currentAreaId) {
        this.currentAreaId = currentAreaId;
    }

    @Column(name = "Licence_No")
    public String getLicenceNo() {
        return this.licenceNo;
    }

    public void setLicenceNo(String licenceNo) {
        this.licenceNo = licenceNo;
    }

    @Column(name = "Licence_Type")
    public String getLicenceType() {
        return this.licenceType;
    }

    public void setLicenceType(String licenceType) {
        this.licenceType = licenceType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "Licence_Expiry_Date", length = 0)
    public Date getLicenceExpiryDate() {
        return this.licenceExpiryDate;
    }

    public void setLicenceExpiryDate(Date licenceExpiryDate) {
        this.licenceExpiryDate = licenceExpiryDate;
    }

    

    @Column(name = "Car_Type_Automatic", length = 1)
    public Character getCarTypeAutomatic() {
        return this.carTypeAutomatic;
    }

    public void setCarTypeAutomatic(Character carTypeAutomatic) {
        this.carTypeAutomatic = carTypeAutomatic;
    }

    @Column(name = "Car_Type_Manual", length = 1)
    public Character getCarTypeManual() {
        return this.carTypeManual;
    }

    public void setCarTypeManual(Character carTypeManual) {
        this.carTypeManual = carTypeManual;
    }

    @Column(name = "Rating_Id")
    public Integer getRatingId() {
        return this.ratingId;
    }

    public void setRatingId(Integer ratingId) {
        this.ratingId = ratingId;
    }

    @Column(name = "Reference_Name")
    public String getReferenceName() {
        return this.referenceName;
    }

    public void setReferenceName(String referenceName) {
        this.referenceName = referenceName;
    }

    @Column(name = "Reference_Number", length = 16777215)
    public String getReferenceNumber() {
        return this.referenceNumber;
    }

    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }

    @Column(name = "Medical_History")
    public String getMedicalHistory() {
        return this.medicalHistory;
    }

    public void setMedicalHistory(String medicalHistory) {
        this.medicalHistory = medicalHistory;
    }

    @Column(name = "Accident_History")
    public String getAccidentHistory() {
        return this.accidentHistory;
    }

    public void setAccidentHistory(String accidentHistory) {
        this.accidentHistory = accidentHistory;
    }


    @Column(name = "Job_Pref_Individual_Temp")
    public Character getJobPrefIndividualTemp() {
        return jobPrefIndividualTemp;
    }

    public void setJobPrefIndividualTemp(Character jobPrefIndividualTemp) {
        this.jobPrefIndividualTemp = jobPrefIndividualTemp;
    }

    @Column(name = "Job_Pref_Individual_Perm")
    public Character getJobPrefIndividualPerm() {
        return jobPrefIndividualPerm;
    }

    public void setJobPrefIndividualPerm(Character jobPrefIndividualPerm) {
        this.jobPrefIndividualPerm = jobPrefIndividualPerm;
    }

    @Column(name = "Job_Pref_Individual_Adhoc")
    public Character getJobPrefIndividualAdhoc() {
        return jobPrefIndividualAdhoc;
    }

    public void setJobPrefIndividualAdhoc(Character jobPrefIndividualAdhoc) {
        this.jobPrefIndividualAdhoc = jobPrefIndividualAdhoc;
    }

    @Column(name = "Job_Pref_Corporate_Temp")
    public Character getJobPrefCorporateTemp() {
        return jobPrefCorporateTemp;
    }

    public void setJobPrefCorporateTemp(Character jobPrefCorporateTemp) {
        this.jobPrefCorporateTemp = jobPrefCorporateTemp;
    }

    @Column(name = "Job_Pref_Corporate_Perm")
    public Character getJobPrefCorporatePerm() {
        return jobPrefCorporatePerm;
    }

    public void setJobPrefCorporatePerm(Character jobPrefCorporatePerm) {
        this.jobPrefCorporatePerm = jobPrefCorporatePerm;
    }

    @Column(name = "Job_Pref_Corporate_Adhoc")
    public Character getJobPrefCorporateAdhoc() {
        return jobPrefCorporateAdhoc;
    }

    public void setJobPrefCorporateAdhoc(Character jobPrefCorporateAdhoc) {
        this.jobPrefCorporateAdhoc = jobPrefCorporateAdhoc;
    }

    @Column(name = "Eye_Sight")
    public String getEyeSight() {
        return eyeSight;
    }

    public void setEyeSight(String eyeSight) {
        this.eyeSight = eyeSight;
    }

    @Column(name = "Diabetes")
    public String getDiabetes() {
        return Diabetes;
    }

    public void setDiabetes(String diabetes) {
        Diabetes = diabetes;
    }

    @OneToMany(mappedBy = "driverMaster")
    @Cascade(value = CascadeType.ALL)
    public Set<DriverContact> getDriverContacts() {
        return driverContacts;
    }
    
    public void setDriverContacts(Set<DriverContact> driverContacts) {
        this.driverContacts = driverContacts;
    }
    
    @OneToMany(mappedBy = "driverMaster")
    @Cascade(value = CascadeType.ALL)
    public Set<DriverAddress> getDriverAddresses() {
        return driverAddresses;
    }

    public void setDriverAddresses(Set<DriverAddress> driverAddresses) {
        this.driverAddresses = driverAddresses;
    }
    
    @OneToMany(mappedBy = "driverMaster")
    @Cascade(value = CascadeType.ALL)
    public Set<DriverEducation> getDriverEducations() {
        return driverEducations;
    }

    public void setDriverEducations(Set<DriverEducation> driverEducations) {
        this.driverEducations = driverEducations;
    }

}
