package com.company.carrental.services.core.dto;

// default package
// Generated 17 Nov, 2012 7:41:40 PM by Hibernate Tools 3.4.0.CR1


/**
 * DriverMaster generated by hbm2java
 */
public class SaveDriverApplicationInputDto implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -7685823457397095948L;
    private DriverMasterDto driverMasterDto;

    public DriverMasterDto getDriverMasterDto() {
        return driverMasterDto;
    }

    public void setDriverMasterDto(DriverMasterDto driverMasterDto) {
        this.driverMasterDto = driverMasterDto;
    }
    
    
}
